tinyMCE.addI18n('en.advanced',{
style_select:"Stiler",
font_size:"Fontstørrelse",
fontdefault:"Fontfamilie",
block:"Format",
paragraph:"Avsnitt",
div:"Div",
address:"Adresse",
pre:"Preformattert",
h1:"Overskrift 1",
h2:"Overskrift 2",
h3:"Overskrift 3",
h4:"Overskrift 4",
h5:"Overskrift 5",
h6:"Overskrift 6",
blockquote:"Blockquote",
code:"Kode",
samp:"Kodeprøve",
dt:"Definisjon term ",
dd:"Definisjon beskrivelse",
bold_desc:"Halvfet (Ctrl+B)",
italic_desc:"Kursiv (Ctrl+I)",
underline_desc:"Understreking (Ctrl+U)",
striketrough_desc:"Gjennomstreking",
justifyleft_desc:"Venstrejustert",
justifycenter_desc:"Midstilt",
justifyright_desc:"Høyrejustert",
justifyfull_desc:"Blokkjustert",
bullist_desc:"Punktmering",
numlist_desc:"Nummerering",
outdent_desc:"Rykk ut",
indent_desc:"Rykk inn",
undo_desc:"Angre (Ctrl+Z)",
redo_desc:"Gjør om (Ctrl+Y)",
link_desc:"Sett inn/rediger lenke",
unlink_desc:"Fjern lenke",
image_desc:"Sett inn/rediger bilde",
cleanup_desc:"Rydd opp i kildekode",
code_desc:"Rediger HTML kilde",
sub_desc:"Senket skrift",
sup_desc:"Hevet skrift",
hr_desc:"Sett inn vannrett linjal",
removeformat_desc:"Fjern formattering",
custom1_desc:"Din egen beskrivelse her",
forecolor_desc:"Velg tekstfarge",
backcolor_desc:"Velg bakgrunnsvarge",
charmap_desc:"Sett inn eget tegn",
visualaid_desc:"Hjelpelinjer/usynlige elementer av/på",
anchor_desc:"Sett inn/rediger anker",
cut_desc:"Klipp ut",
copy_desc:"Kopier",
paste_desc:"Lim inn",
image_props_desc:"Bildeegenskaper",
newdocument_desc:"Nytt dokument",
help_desc:"Hjelp",
blockquote_desc:"Blockquote",
clipboard_msg:"Kopier/Klipp ut/Lim inn er ikke tilgjengelig i Mozilla og Firefox.\r\nVil du ha mer informasjon om dette?",
path:"Filsti",
newdocument:"Er du sikker på at du vil slette alt innhold?",
toolbar_focus:"Hopp til verktøyknapper - Alt+Q, Hopp til editor - Alt-Z, Hopp til elementsti - Alt-X",
more_colors:"Flere farger"
});