tinyMCE.addI18n('en.advanced',{
style_select:"Estilos",
font_size:"Tamanho da fonte",
fontdefault:"Família da fonte",
block:"Formato",
paragraph:"Parágrafo",
div:"Div",
address:"Endereço",
pre:"Pre-formatado",
h1:"Cabeçalho 1",
h2:"Cabeçalho 2",
h3:"Cabeçalho 3",
h4:"Cabeçalho 4",
h5:"Cabeçalho 5",
h6:"Cabeçalho 6",
blockquote:"Blockquote",
code:"Código",
samp:"Código exemplo",
dt:"Termo de definição ",
dd:"Descrição da definição",
bold_desc:"Negrito (Ctrl+B)",
italic_desc:"Itálico (Ctrl+I)",
underline_desc:"Sublinhado (Ctrl+U)",
striketrough_desc:"Tachado",
justifyleft_desc:"Alinhar a esquerda",
justifycenter_desc:"Alinhar ao centro",
justifyright_desc:"Alinhar a direita",
justifyfull_desc:"Justificado",
bullist_desc:"Lista desordenada",
numlist_desc:"Lista ordenada",
outdent_desc:"Reduzir recuo",
indent_desc:"Aumentar recuo",
undo_desc:"Desfazer (Ctrl+Z)",
redo_desc:"Refazer (Ctrl+Y)",
link_desc:"Inserir/editar link",
unlink_desc:"Remover link",
image_desc:"Inserir/editar imagem",
cleanup_desc:"Limpar descrição",
code_desc:"Editar fonte HTML",
sub_desc:"Subscrito",
sup_desc:"Sobrescrito",
hr_desc:"Inserir régua horizontal",
removeformat_desc:"Remover formatação",
custom1_desc:"Sua descrição customizada aqui",
forecolor_desc:"Selecione a cor do texto",
backcolor_desc:"Selecione a cor de fundo",
charmap_desc:"Inserir caracter customizado",
visualaid_desc:"Alternar linhas de guia/elementos invisíveis",
anchor_desc:"Inserir/editar âncora",
cut_desc:"Recortar",
copy_desc:"Copiar",
paste_desc:"Colar",
image_props_desc:"Propriedades da imagem",
newdocument_desc:"Novo documento",
help_desc:"Ajuda",
blockquote_desc:"Blockquote",
clipboard_msg:"Copiar/Colar não disponível no Mozilla e Firefox.\r\nVocê deseja mais informações sobre esse recurso?",
path:"Caminho",
newdocument:"Você tem certeza que deseja limpar todo conteúdo?",
toolbar_focus:"Saltar para botões de ferramenta - Alt+Q, Saltar para editor - Alt-Z, Saltar para caminho do elemento - Alt-X",
more_colors:"Mais cores"
});
