<?php

namespace go\core\mail;

use go\core\fs\Blob;
use Swift_Attachment;

class Attachment extends Swift_Attachment {

	/**
	 * Provide Blob. Extracts path from blob and returns attachment
	 * 
	 * @param Blob $blob
	 * @return Swift_Attachment
	 */
    public static function fromBlob(Blob $blob) {
        return Swift_Attachment::fromPath($blob->path());
		}

		public static function fromPath(string $path, $contentType = null)
		{
			return parent::fromPath($path, $contentType); // TODO: Change the autogenerated stub
		}

		public function setFilename($filename)
		{
			return parent::setFilename($filename); // TODO: Change the autogenerated stub
		}

		public function getFilename()
		{
			return parent::getFilename(); // TODO: Change the autogenerated stub
		}


		public function getId()
		{
			return parent::getId(); // TODO: Change the autogenerated stub
		}

		public function setId($id)
		{
			return parent::setId($id); // TODO: Change the autogenerated stub
		}

}