#!/bin/sh

set -e

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.mysql
    dbc_go groupoffice-com $@
fi

if [ "$1" = "purge" ]; then
    rm -f /etc/groupoffice/config-db.php
		rm -f /etc/groupoffice/config.php
    if which ucf >/dev/null 2>&1; then
    	ucf --purge /etc/groupoffice/config-db.php
    fi
		db_purge
fi

#DEBHELPER#

exit 0
