DROP TABLE IF EXISTS `sync_contacts_maps`;
DROP TABLE IF EXISTS `sync_contacts_syncs`;
DROP TABLE IF EXISTS `sync_devices`;
DROP TABLE IF EXISTS `sync_events_maps`;
DROP TABLE IF EXISTS `sync_events_syncs`;
DROP TABLE IF EXISTS `sync_settings`;
DROP TABLE IF EXISTS `sync_tasks_maps`;
DROP TABLE IF EXISTS `sync_tasks_syncs`;
DROP TABLE IF EXISTS `sync_addressbook_user`;
DROP TABLE IF EXISTS `sync_tasklist_user`;
DROP TABLE IF EXISTS `sync_calendar_user`, `sync_note_categories_user`, `sync_user_note_book`;