#!/bin/bash
set -e

# Use debconf.
. /usr/share/debconf/confmodule


db_get groupoffice-mailserver/domain
domain="$RET"

#if [ ! -e "/etc/groupoffice/config-mailserver.inc.php" ]
#then
	cat /etc/groupoffice/config-db.php > /etc/groupoffice/config-mailserver.inc.php
	echo -e "\$domain='$domain';\n" >> /etc/groupoffice/config-mailserver.inc.php

	chown root:www-data /etc/groupoffice/config-mailserver.inc.php
	chmod 640 /etc/groupoffice/config-mailserver.inc.php

#fi






touch /etc/postfix/main.cf

if (  grep -q 'mysql_virtual' /etc/postfix/main.cf ); then
	echo Postfix is already configured for MySQL virtual hosts. Skipping Postfix configuration
else
	echo Configuring Postfix

	cp /etc/postfix/main.cf /etc/postfix/main.cf.gobak.$2

	#postconf -e 'recipient_delimiter = +'
	#postconf -e 'inet_interfaces = all'
	postconf -e 'mydestination = $myhostname, localhost, localhost.localdomain'
	postconf -e 'proxy_read_maps = $local_recipient_maps $mydestination $virtual_alias_maps $virtual_alias_domains $virtual_mailbox_maps $virtual_mailbox_domains $relay_recipient_maps $relay_domains $canonical_maps $sender_canonical_maps $recipient_canonical_maps $relocated_maps $transport_maps $mynetworks $virtual_mailbox_limit_maps'
	postconf -e 'relay_domains = proxy:mysql:/etc/postfix/mysql_relay_domains_maps.cf'
	postconf -e 'virtual_alias_domains ='
	postconf -e 'virtual_alias_maps = proxy:mysql:$config_directory/mysql_virtual_alias_maps.cf'
	postconf -e 'virtual_mailbox_domains = proxy:mysql:$config_directory/mysql_virtual_domains_maps.cf'
	postconf -e 'virtual_mailbox_maps = proxy:mysql:$config_directory/mysql_virtual_mailbox_maps.cf'
	postconf -e 'virtual_mailbox_base = /home/vmail'
	postconf -e 'virtual_minimum_uid = 150'
	postconf -e 'virtual_uid_maps = static:150'
	postconf -e 'virtual_gid_maps = static:8'
	#postconf -e 'virtual_create_maildirsize = yes'
	#postconf -e 'virtual_mailbox_extended = yes'
	postconf -e 'virtual_mailbox_limit_maps = proxy:mysql:/etc/postfix/mysql_virtual_mailbox_limit_maps.cf'
	#postconf -e 'virtual_mailbox_limit_override = yes'
	#postconf -e 'virtual_maildir_limit_message = "The user you are trying to reach has exceeded their quota."'
	#postconf -e 'virtual_overquota_bounce = yes'

	#we direct everything to dovecot in main.cf
	#postconf -e 'transport_maps = proxy:mysql:/etc/postfix/mysql_virtual_transports.cf'

	postconf -e 'smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_non_fqdn_sender, reject_non_fqdn_recipient, reject_unauth_destination, reject_unauth_pipelining, reject_invalid_hostname, reject_unknown_sender_domain, reject_rbl_client zen.spamhaus.org, reject_rhsbl_sender dsn.fc-ignorant.org, permit'
	postconf -e 'smtpd_data_restrictions = reject_unauth_pipelining, reject_multi_recipient_bounce, permit'


	#address mapping is done after spamassassin
	postconf -e 'receive_override_options = no_address_mappings'

	#transport map for autoreply or vacation (old)
	#postconf -e 'transport_maps = hash:/etc/postfix/transport';
	#postconf -e 'vacation_destination_recipient_limit = 1';

	# dovecot handles delivery
	postconf -e virtual_transport=dovecot
	postconf -e dovecot_destination_recipient_limit=1

	postconf -e 'message_size_limit = 20480000'

	postconf -e 'content_filter=smtp-amavis:[127.0.0.1]:10024'

fi

#check if user vmail exists
if  ! id vmail 1>/dev/null 2>&1 ; then
	echo Adding vmail user
	useradd -r -u 150 -g mail -d /home/vmail -s /sbin/nologin -c "Virtual Mailbox" vmail
fi

adduser clamav amavis

if [ ! -x /home/vmail ]; then
	mkdir /home/vmail	
fi

chmod 770 /home/vmail
chown vmail:mail /home/vmail


echo setting up dovecot
chmod 600 /etc/dovecot/*.conf
chown vmail /etc/dovecot/*.conf


#For IMAP ACL support
chown vmail:mail /var/lib/dovecot
touch /var/lib/dovecot/shared-mailboxes.db
chown vmail:mail /var/lib/dovecot/shared-mailboxes.db


#check if user spamd exists. Exit code 0 means it exists
if  ! id spamd 1>/dev/null 2>&1 ; then
	groupadd -g 5001 spamd
	useradd -u 5001 -g spamd -s /sbin/nologin -d /var/lib/spamassassin spamd
	mkdir -p /var/lib/spamassassin	
fi

#chown spamd:spamd /var/lib/spamassassin
#changed since jessie ?
chown -R debian-spamd:debian-spamd /var/lib/spamassassin

FILE=/etc/default/spamassassin
if (  grep -q 'Group-Office' $FILE ); then
	echo Spamassassin was already configured
	FILE=$FILE.$2
else
	echo Spamassassin configured by Group-Office
	cp /etc/default/spamassassin /etc/spamassassin/spamassassin.beforegroupoffice.$2
fi
cp /usr/share/groupoffice-mailserver/tpl/etc/default/spamassassin $FILE


FILE=/etc/spamassassin/local.cf
if (  grep -q 'Group-Office' $FILE ); then
	echo Spamassassin local.cf was already configured
	FILE=$FILE.$2
else
	echo Spamassassin local.cf configured by Group-Office
	cp /etc/spamassassin/local.cf /etc/spamassassin/local.cf.beforegroupoffice.$2
fi
cp /usr/share/groupoffice-mailserver/tpl/etc/spamassassin/local.cf $FILE


FILE=/etc/postfix/master.cf
if (  grep -q 'Group-Office' $FILE ); then
	echo Postfix master.cf was already configured
	FILE=$FILE.$2
else
	echo Postfix master.cf configured by Group-Office
	cp /etc/postfix/master.cf /etc/postfix/master.cf.beforegroupoffice.$2
fi
cp /usr/share/groupoffice-mailserver/tpl/etc/postfix/master.cf $FILE


echo Setting up pyzor and razor for amavis
sudo -u amavis -H bash -c "razor-admin -create"
sudo -u amavis -H bash -c "razor-admin -register"
sudo -u amavis -H bash -c "pyzor discover"


php /usr/share/groupoffice-mailserver/configure.php
php /usr/share/groupoffice-mailserver/installpostfixadmin.php

invoke-rc.d spamassassin restart 3> /dev/null || true
invoke-rc.d postfix restart 3> /dev/null || true
invoke-rc.d dovecot restart 3> /dev/null || true
invoke-rc.d clamav-daemon restart 3> /dev/null || true
invoke-rc.d clamav-freshclam restart 3> /dev/null || true

php /usr/share/groupoffice-mailserver/addadminaccount.php

#DEBHELPER#

exit 0
