#!/bin/sh
set -e

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule
    # Remove my changes to the db.
    db_purge

		rm -f /etc/postfix/mysql_virtual_alias_maps.cf
		rm -f /etc/postfix/mysql_virtual_domains_maps.cf
		rm -f /etc/postfix/mysql_virtual_mailbox_limit_maps.cf
		rm -f /etc/postfix/mysql_virtual_mailbox_maps.cf
		rm -f /etc/postfix/mysql_virtual_transports.cf
		rm -f /etc/postfix/mysql_relay_domains_maps.cf
		rm -f /etc/postfix/transport
		rm -f /etc/dovecot/dovecot-sql.conf
		rm -f /etc/groupoffice/vacation
		rm -f /etc/groupoffice/globalconfig.inc.php
		rm -f /etc/groupoffice/config-mailserver.inc.php
fi

#DEBHELPER#

exit 0