DROP TABLE IF EXISTS `fs_files`;
DROP TABLE IF EXISTS `fs_folders`;
DROP TABLE IF EXISTS `fs_notifications`;
DROP TABLE IF EXISTS `fs_notification_messages`;
DROP TABLE IF EXISTS `fs_statuses`;
DROP TABLE IF EXISTS `fs_status_history`;
DROP TABLE IF EXISTS `fs_templates`;
DROP TABLE IF EXISTS `fs_new_files`;
DROP TABLE IF EXISTS `go_links_6`;
DROP TABLE IF EXISTS `go_links_17`;
DROP TABLE IF EXISTS `cf_6`;
DROP TABLE IF EXISTS `fs_shared_cache`;
DROP TABLE IF EXISTS `fs_versions`;
DROP TABLE IF EXISTS `fs_shared_root_folders`;
DROP TABLE IF EXISTS `fs_files_custom_fields`;
DROP TABLE IF EXISTS `fs_folders_custom_fields`;
DROP TABLE IF EXISTS `fs_bookmarks`, `fs_filehandlers`, `fs_folder_pref`;