DROP TABLE IF EXISTS test_a;
DROP TABLE IF EXISTS test_b;
DROP TABLE IF EXISTS test_c;
DROP TABLE IF EXISTS test_a_has_many;
DROP TABLE IF EXISTS test_a_has_one;
DROP TABLE if EXISTS test_a_map;
DROP TABLE if EXISTS test_d;