#!/bin/bash
set -e

# Use debconf.
. /usr/share/debconf/confmodule


db_get groupoffice-servermanager/wildcarddomain
wildcarddomain="$RET"

cat /etc/groupoffice/config-db.php > /etc/groupoffice/config-servermanager.inc.php
echo -e "\$wildcarddomain='$wildcarddomain';\n" >> /etc/groupoffice/config-servermanager.inc.php

chown root:www-data /etc/groupoffice/config-servermanager.inc.php
chmod 640 /etc/groupoffice/config-servermanager.inc.php


echo "Running configure.php"
php /usr/share/groupoffice-servermanager/configure.php

echo "Running installservermanager.php"
php /usr/share/groupoffice-servermanager/installservermanager.php

a2enmod vhost_alias

#chown -R www-data:www-data /home/govhosts

invoke-rc.d apache2 reload 3> /dev/null || true

/usr/share/groupoffice/groupofficecli.php -r=servermanager/installation/upgradeAll -c=/etc/groupoffice/config.php -q

#DEBHELPER#

exit 0
