<?php

namespace go\core\model;

use go\core\db\Criteria;
use \go\core\validate\ErrorCode;
use go\core\jmap\Entity;
use go\core\orm\Filters;
use go\core\orm\Mapping;
use go\core\orm\Query;
use go\core\orm\Relation;
use go\core\util\DateTime;

class AppPassword extends Entity
{
	public ?string $id;

	public string $userId;

	public string $label;

	protected string $passwordHash;

	public DateTime $createdAt;

	public ?DateTime $lastUsedAt;

	public ?string $lastUsedIp;

	public ?DateTime $revokedAt;

	/** @var AppPasswordScope[] */
	public array $scopes;

	protected static function defineMapping(): Mapping
	{
		return parent::defineMapping()
			->addTable("core_app_password", "cap")
			->add("scopes", Relation::array(AppPasswordScope::class)->keys(['id' => 'appPasswordId']));
	}

	public static function defineFilters(): Filters
	{
		return parent::defineFilters()
			->add('user', function (Criteria $criteria, $value) {
				$criteria->where('userId', '=', $value);
			})
			->add('isRevoked', function (Criteria $criteria, $value) {
				if ($value) {
					$criteria->andWhere('revokedAt', '!=', null);
				} else {
					$criteria->andWhere('revokedAt', '=', null);
				}
			});
	}

	/**
	 * Non admins can only see their own app passwords in queries and changes.
	 */
	public static function applyAclToQuery(Query $query, int $level = Acl::LEVEL_READ, int|null $userId = null, array|null $groups = null): Query
	{
		$userId = $userId ?? go()->getUserId();
		if (!User::isAdminById($userId)) {
			$query->andWhere('cap.userId', '=', $userId);
		}

		return $query;
	}

	protected function internalGetPermissionLevel(): int
	{
		if ($this->userId == go()->getUserId() || go()->getAuthState()->isAdmin()) {
			return Acl::LEVEL_MANAGE;
		} else {
			return 0;
		}
	}

	/**
	 * Plain text secret, only available on the instance that created it so it can be returned once to the client.
	 */
	private ?string $plainSecret = null;

	/**
	 * The generated secret. Only returned in the response of the creating request. It's never stored.
	 */
	public function getSecret(): ?string
	{
		return $this->plainSecret;
	}

	public static function readOnlyProps(): array
	{
		return array_merge(parent::readOnlyProps(), ['createdAt', 'lastUsedAt', 'lastUsedIp']);
	}

	/**
	 * Whether the given string has the format of a generated secret. Anything else can't be an app password.
	 */
	public static function looksLikeSecret(string $password): bool
	{
		return preg_match('/^[a-f0-9]{32}$/', $password) === 1;
	}

	/**
	 * App passwords are long random strings generated by the server, so a fast hash is sufficient and
	 * a slow one (bcrypt) would only cost CPU on every DAV / ActiveSync request.
	 */
	private static function hashSecret(string $secret): string
	{
		return hash('sha256', $secret);
	}

	protected function internalValidate()
	{
		if (!$this->isNew() && $this->isModified('userId')) {
			$this->setValidationError('userId', ErrorCode::FORBIDDEN, 'The owner of an app password can\'t be changed');
		}

		if ($this->isModified('userId') && $this->userId != go()->getUserId() && !go()->getAuthState()->isAdmin()) {
			$this->setValidationError('userId', ErrorCode::FORBIDDEN, 'You can only create app passwords for yourself');
		}

		// A revoked password can't be reactivated.
		$revoked = $this->getModified(['revokedAt']);
		if (isset($revoked['revokedAt']) && $revoked['revokedAt'][1] !== null) {
			$this->setValidationError('revokedAt', ErrorCode::FORBIDDEN, 'A revoked app password can\'t be reactivated');
		}

		parent::internalValidate();
	}

	protected function internalSave(): bool
	{
		if ($this->isNew()) {
			$this->plainSecret = bin2hex(random_bytes(16));
			$this->passwordHash = self::hashSecret($this->plainSecret);
		}

		return parent::internalSave();
	}

	public function verifyPassword(string $password): bool
	{
		return hash_equals($this->passwordHash, self::hashSecret($password));
	}

}
